# This workflow creates a template based on the repository and publishes it to the registry
name: Templatify workflow

on:
  workflow_dispatch:

permissions:
  packages: read
  
jobs:
  templatify:
    name: Templatify
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/simatic-ax/ci-images/apax-ci-image:3.5.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Templatify repository
        uses: simatic-ax/actions/apax-templatify@v3
        with:
          version: 1.0.0

      - name: Pack the template
        uses: simatic-ax/actions/apax-pack@v3 
        with:
          version: 1.0.0
      
      - name: Login to required registries
        uses: simatic-ax/actions/apax-login@v3
        with:
          apax-token: ${{ secrets.APAX_TOKEN }}
          registries: |
            https://npm.pkg.github.com/,${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish template
        uses: simatic-ax/actions/apax-publish@v3
        with:
          registries: |
            https://npm.pkg.github.com/
          tag: 1.0.0
